### PR TITLE
added auto-resize feature for avatar

### PR DESCRIPTION
**Pull request by cboelter**
This PR adds the possibility to resize avatar images automatically to the configured sizes.
So there is no need for manually resizing them by the user.

Please check this PR and give me feedback :)

### CODE REVIEW

**Comment by cboelter** [comment]
No feedback since 15 days :( ... is the PR not good? We need this feature.

**Comment by qzminski** [comment]
Except that one comment I posted I think it is okay. @Toflar @aschempp

**Comment by Toflar** [comment]
Yeah, nothing happened since your comment so no need for us to check :)

**Comment by qzminski** [comment]
Merged in d8d4a8a.

**Pull request closed without merging**
