### PR TITLE
Added support for jCrop's allowResize setting

### PR DESCRIPTION
**Pull request by silenzium**
The resulting image will be saved with the dimensions from the extension config but the user can resize the rectangle, so one can choose an area from a bigger image.

( This is my very first pull reuquest ever on Github, so I hope I'm doin' right...)

### CODE REVIEW

**Comment by Toflar** [comment]
@qzminski can you check this on occasion?

**Comment by qzminski** [comment]
Looks good to me.

**Comment by silenzium** [comment]
will this be merged or do I have to do something since I'm the OP...?

**Comment by qzminski** [comment]
Merged to ```develop```, sorry for the delay.

**Comment by silenzium** [comment]
no worries, thank you!

**Pull request merged**
